version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies
      - cd frontend
      - npm install
      - cd ..
      - echo Installing backend dependencies
      - cd backend
      - npm install
      - cd ..

  build:
    commands:
      - echo Building frontend
      - cd frontend
      - npm run build --prod
      - cd ..
      - echo Building backend
      - cd backend
      - npm run build
      - cd ..

artifacts:
  files:
    - '**/*'
  base-directory: 'backend/dist'

env:
  secrets-manager:
    DB_SERVER_URL: "your-secrets-manager-arn:DB_SERVER_URL"
    JWT_PRIVATE_KEY: "your-secrets-manager-arn:JWT_PRIVATE_KEY"
