version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=mean-stack-tbl

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
