AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack for deploying a MEAN stack application to Elastic Beanstalk

Parameters:
  JwtPrivateKey:
    Type: String
  Port:
    Type: String

Resources:
  MyElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: "mean-stack-app"

  MyElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      EnvironmentName: "mean-stack-env"
      ApplicationName: !Ref MyElasticBeanstalkApplication
      SolutionStackName: "64bit Amazon Linux 2 v5.4.7 running Node.js 14"
      OptionSettings:
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: JWT_PRIVATE_KEY
          Value: !Ref JwtPrivateKey
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: PORT
          Value: !Ref Port
      VersionLabel: !Ref ApplicationVersion

  ApplicationVersion:
    Type: "AWS::ElasticBeanstalk::ApplicationVersion"
    Properties:
      ApplicationName: !Ref MyElasticBeanstalkApplication
      Description: "Version 1.0"
      SourceBundle:
        S3Bucket: "mean-stack-sam"
        S3Key: "mean-stack-app.zip"
