name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Ensure this matches the version in your Elastic Beanstalk configuration

    - name: Install dependencies and build frontend
      run: |
        cd frontend
        npm install
        npm run build -- --configuration production

    - name: Prepare application for deployment
      run: |
        mkdir deploy
        cp -r backend deploy/
        cp -r frontend/dist deploy/frontend
        cp mean-stack-template.yml deploy/
        cd deploy
        zip -r mean-stack-app.zip .

    - name: Verify zip file creation
      run: ls -lh deploy/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust the region as needed

    - name: Upload to S3
      run: |
        aws s3 cp deploy/mean-stack-app.zip s3://mean-stack-sam/mean-stack-app.zip

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation create-stack \
          --stack-name MEANStackApp \
          --template-url "https://s3.amazonaws.com/mean-stack-sam/mean-stack-template.yml" \
          --parameters ParameterKey=JwtPrivateKey,ParameterValue="6553c1f160d95c7bea24f667" ParameterKey=Port,ParameterValue="3000" \
          --capabilities CAPABILITY_NAMED_IAM || \
        aws cloudformation update-stack \
          --stack-name MEANStackApp \
          --template-url "https://s3.amazonaws.com/mean-stack-sam/mean-stack-template.yml" \
          --parameters ParameterKey=JwtPrivateKey,ParameterValue="6553c1f160d95c7bea24f667" ParameterKey=Port,ParameterValue="3000" \
          --capabilities CAPABILITY_NAMED_IAM
